notifications:
  email: false

language: c

# enable "Build pushes" and "Build pull requests" in Travis CI
# - pull requests will always be built
# - only build pushes to master
branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6

env:
  # add target platforms to build matrix
  # Note that each variable is actually exported - PLATFORM and EXCLUDED_TESTS are picked up
  # as environment variables in the makefile
  # lint is a target so we don't need to lint multiple times
  # Travis does not support SocketCAN
  - TARGET=build_all PLATFORM=x86
  - TARGET=build_all PLATFORM=stm32f0xx
  - TARGET=test_all PLATFORM=x86 EXCLUDED_TESTS=can can_hw
  - TARGET=lint

before_script:
  # install GCC ARM from GNU ARM Embedded Toolchain PPA and GCC 6
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get -y install gcc-arm-embedded
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

  # build GNU Make 4.1 from source
  - wget http://ftp.gnu.org/gnu/make/make-4.1.tar.gz
  - tar xvf make-4.1.tar.gz
  - cd make-4.1
  - ./configure
  - make
  - sudo make install
  - cd ..
  - rm -rf make-4.1

  # add Make to path
  - export PATH=/usr/local/bin/:$PATH

script:
  - make $TARGET
