notifications:
  email: false

language: c

# enable "Build pushes" and "Build pull requests" in Travis CI
# - pull requests will always be built
# - only build pushes to master
branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      # ubuntu-toolchain-r-test
      - gcc-6
      - g++-6
      # llvm-toolchain-trusty-5.0
      - clang-5.0
      - clang-format-5.0
      # python
      - python3

before_script:
  # create directory that will be on the PATH
  - mkdir -p $HOME/bin
  - export PATH=$HOME/bin/:$PATH

  # install GCC ARM from GNU ARM Embedded Toolchain PPA and GCC 6
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get -qq update
  - sudo apt-get -y install gcc-arm-embedded
  - ln -sf `which gcc-6` $HOME/bin/gcc

  # build GNU Make 4.1 from source
  - wget http://ftp.gnu.org/gnu/make/make-4.1.tar.gz
  - tar xvf make-4.1.tar.gz
  - cd make-4.1
  - ./configure --prefix=$HOME
  - make
  - make install
  - cd ..
  - rm -rf make-4.1

  # clang
  - ln -sf `which clang-5.0` $HOME/bin/clang
  - ln -sf `which clang-format-5.0` $HOME/bin/clang-format
  - clang-format --version

  # Install pylint for python3
  - pip3 install -U pylint
  - pylint --version

script:
  - make build_all PLATFORM=x86
  - make build_all PLATFORM=stm32f0xx
  - make test_all PLATFORM=x86
  - make lint
  - make test_format
