#pragma once

#include <stdbool.h>

#include "can_msg.h"

// For setting the CAN device
typedef enum {
  CAN_DEVICE_PLUTUS = 0,
  CAN_DEVICE_CHAOS = 1,
  CAN_DEVICE_TELEMETRY = 2,
  CAN_DEVICE_LIGHTS_FRONT = 3,
  CAN_DEVICE_LIGHTS_REAR = 4,
  CAN_DEVICE_MOTOR_CONTROLLER = 5,
  CAN_DEVICE_DRIVER_CONTROLS = 6,
  CAN_DEVICE_DRIVER_DISPLAY = 7,
  CAN_DEVICE_SOLAR_MASTER_FRONT = 8,
  CAN_DEVICE_SOLAR_MASTER_REAR = 9,
  CAN_DEVICE_SENSOR_BOARD = 10,
  NUM_CAN_DEVICES = 11
} CanDevice;

// For setting the CAN message ID
typedef enum {
  CAN_MESSAGE_BPS_FAULT = 0,
  CAN_MESSAGE_BATTERY_RELAY = 1,
  CAN_MESSAGE_MAIN_RELAY = 2,
  CAN_MESSAGE_SOLAR_RELAY = 3,
  CAN_MESSAGE_POWER_STATE = 4,
  CAN_MESSAGE_OVUV_DCDC_AUX = 16,
  CAN_MESSAGE_MC_ERROR_LIMITS = 17,
  CAN_MESSAGE_THROTTLE = 18,
  CAN_MESSAGE_MOTOR_CRUISE = 19,
  CAN_MESSAGE_DIRECTION_SELECTOR = 20,
  CAN_MESSAGE_LIGHTS_STATES = 24,
  CAN_MESSAGE_HORN = 25,
  CAN_MESSAGE_MECHANICAL_BRAKE = 26,
  CAN_MESSAGE_BATTERY_SOC = 31,
  CAN_MESSAGE_BATTERY_VCT = 32,
  CAN_MESSAGE_MOTOR_CONTROLLER_VC = 35,
  CAN_MESSAGE_MOTOR_VELOCITY = 36,
  CAN_MESSAGE_MOTOR_CONTROLLER_TEMPS = 37,
  CAN_MESSAGE_MOTOR_AMP_HR = 38,
  CAN_MESSAGE_ODOMETER = 39,
  CAN_MESSAGE_AUX_DCDC_VC = 43,
  CAN_MESSAGE_DCDC_TEMPS = 44,
  CAN_MESSAGE_SOLAR_DATA_FRONT = 45,
  CAN_MESSAGE_SOLAR_DATA_REAR = 46,
  CAN_MESSAGE_STEERING_ANGLE = 48,
  CAN_MESSAGE_LINEAR_ACCELERATION = 51,
  CAN_MESSAGE_ANGULAR_ROTATION = 52,
  NUM_CAN_MESSAGES = 27
} CanMessage;
