#pragma once
// Shared events for FSMs
#include "event_queue.h"

// ID definitions for the console input events.
typedef enum {
  INPUT_EVENT_PEDAL_WATCHDOG_FAULT = 0,
  INPUT_EVENT_PEDAL_CAN_RX,
  INPUT_EVENT_PEDAL_CAN_TX,
  INPUT_EVENT_PEDAL_CAN_FAULT,
  INPUT_EVENT_PEDAL_UPDATE_REQUESTED,
  INPUT_EVENT_MECHANICAL_BRAKE_PRESSED,
  INPUT_EVENT_MECHANICAL_BRAKE_RELEASED,

  INPUT_EVENT_PEDAL_BRAKE,
  INPUT_EVENT_PEDAL_COAST,
  INPUT_EVENT_PEDAL_ACCEL,
  INPUT_EVENT_PEDAL_FAULT,

  NUM_INPUT_EVENTS,
} InputEvent;
