#pragma once
// Shared events for FSMs
#include "event_queue.h"

// ID definitions for the console input events.
typedef enum {
  INPUT_EVENT_PEDAL_WATCHDOG_FAULT = 0,
  INPUT_EVENT_PEDAL_CAN_RX,
  INPUT_EVENT_PEDAL_CAN_TX,
  INPUT_EVENT_PEDAL_CAN_FAULT,
  INPUT_EVENT_PEDAL_UPDATE_REQUESTED,
  INPUT_EVENT_PEDAL_POWER_STATE_OFF,
  INPUT_EVENT_PEDAL_POWER_STATE_FAULT,
  INPUT_EVENT_MECHANICAL_BRAKE_PRESSED,
  INPUT_EVENT_MECHANICAL_BRAKE_RELEASED,

  INPUT_EVENT_PEDAL_BRAKE,
  INPUT_EVENT_PEDAL_COAST,
  INPUT_EVENT_PEDAL_ACCEL,
  INPUT_EVENT_PEDAL_FAULT,

  // Pedal Power state events
  INPUT_EVENT_PEDAL_POWER_STATE_OFF,
  INPUT_EVENT_PEDAL_POWER_STATE_DRIVE,
  INPUT_EVENT_PEDAL_POWER_STATE_CHARGE,
  INPUT_EVENT_PEDAL_POWER_STATE_FAULT,

  // Pedal Control Stalk events
  INPUT_EVENT_PEDAL_CONTROL_STALK_ANALOG_CC_RESUME,

  // Pedal Centre Console events
  INPUT_EVENT_PEDAL_CENTER_CONSOLE_DIRECTION_DRIVE,
  INPUT_EVENT_PEDAL_CENTER_CONSOLE_DIRECTION_REVERSE,

  // Pedal direction events
  // Direction state events
  INPUT_EVENT_PEDAL_DIRECTION_STATE_NEUTRAL,
  INPUT_EVENT_PEDAL_DIRECTION_STATE_FORWARD,
  INPUT_EVENT_PEDAL_DIRECTION_STATE_REVERSE,

  // Pedal speed event
  INPUT_EVENT_PEDAL_SPEED_UPDATE,

  NUM_INPUT_EVENTS,
} InputEvent;
