#pragma once

#define CENTER_CONSOLE_CONFIG_PIN_LOW_BEAM \
  { GPIO_PORT_A, 0 }
#define CENTER_CONSOLE_CONFIG_PIN_HAZARDS \
  { GPIO_PORT_A, 1 }
#define CENTER_CONSOLE_CONFIG_PIN_DRL \
  { GPIO_PORT_A, 4 }
#define CENTER_CONSOLE_CONFIG_PIN_DRIVE \
  { GPIO_PORT_A, 5 }
#define CENTER_CONSOLE_CONFIG_PIN_NEUTRAL \
  { GPIO_PORT_A, 6 }
#define CENTER_CONSOLE_CONFIG_PIN_REVERSE \
  { GPIO_PORT_A, 7 }
#define CENTER_CONSOLE_CONFIG_PIN_POWER \
  { GPIO_PORT_B, 0 }
#define CENTER_CONSOLE_CONFIG_PIN_5V_MONITOR \
  { GPIO_PORT_B, 1 }

#define CENTER_CONSOLE_CONFIG_PIN_5V_ENABLE \
  { GPIO_PORT_B, 12 }
#define CENTER_CONSOLE_CONFIG_PIN_DISPLAY_ENABLE \
  { GPIO_PORT_B, 8 }
#define CENTER_CONSOLE_CONFIG_PIN_FAN_ENABLE \
  { GPIO_PORT_B, 9 }
