#pragma once

#define CENTER_CONSOLE_CONFIG_PIN_LOW_BEAM \
  { GPIO_PORT_A, 0 }
#define CENTER_CONSOLE_CONFIG_PIN_HAZARDS \
  { GPIO_PORT_A, 1 }
#define CENTER_CONSOLE_CONFIG_PIN_DRL \
  { GPIO_PORT_A, 4 }
#define CENTER_CONSOLE_CONFIG_PIN_DRIVE \
  { GPIO_PORT_A, 5 }
#define CENTER_CONSOLE_CONFIG_PIN_NEUTRAL \
  { GPIO_PORT_A, 6 }
#define CENTER_CONSOLE_CONFIG_PIN_REVERSE \
  { GPIO_PORT_A, 7 }
#define CENTER_CONSOLE_CONFIG_PIN_POWER \
  { GPIO_PORT_B, 0 }
#define CENTER_CONSOLE_CONFIG_PIN_5V_MONITOR \
  { GPIO_PORT_B, 1 }

#define CENTER_CONSOLE_CONFIG_PIN_5V_ENABLE \
  { GPIO_PORT_B, 12 }
#define CENTER_CONSOLE_CONFIG_PIN_DISPLAY_ENABLE \
  { GPIO_PORT_B, 8 }
#define CENTER_CONSOLE_CONFIG_PIN_FAN_ENABLE \
  { GPIO_PORT_B, 9 }

#define CENTER_CONSOLE_CONFIG_PIN_I2C_SDL \
  { GPIO_PORT_B, 10 }
#define CENTER_CONSOLE_CONFIG_PIN_I2C_SDA \
  { GPIO_PORT_B, 11 }

// GPIO Mapping for GPIO expander
#define CENTER_CONSOLE_CONFIG_GPIO_EXPANDER_LED_BPS GPIO_EXPANDER_PIN_0
#define CENTER_CONSOLE_CONFIG_GPIO_EXPANDER_LED_POWER GPIO_EXPANDER_PIN_1
#define CENTER_CONSOLE_CONFIG_GPIO_EXPANDER_LED_REVERSE GPIO_EXPANDER_PIN_2
#define CENTER_CONSOLE_CONFIG_GPIO_EXPANDER_LED_NEUTRAL GPIO_EXPANDER_PIN_3
#define CENTER_CONSOLE_CONFIG_GPIO_EXPANDER_LED_DRIVE GPIO_EXPANDER_PIN_4
#define CENTER_CONSOLE_CONFIG_GPIO_EXPANDER_LED_DRL GPIO_EXPANDER_PIN_5
#define CENTER_CONSOLE_CONFIG_GPIO_EXPANDER_LED_LOW_BEAMS GPIO_EXPANDER_PIN_6
#define CENTER_CONSOLE_CONFIG_GPIO_EXPANDER_LED_HAZARDS GPIO_EXPANDER_PIN_7
