#pragma once

// Not all timers on the stm32f0xx support PWM mode these are the ones that do.
// The number comes from the id of the hardware timer.
typedef enum {
  PWM_TIMER_1 = 0,
  // PWM_TIMER_2,  // Requisitioned to back the soft_timer module.
  PWM_TIMER_3,
  PWM_TIMER_14,
  PWM_TIMER_15,
  PWM_TIMER_16,
  PWM_TIMER_17,
  NUM_PWM_TIMERS,
} PWMTimer;

// AltFn defines:
#define PWM_TIMER_1_GPIO_PA8_ALTFN GPIO_ALTFN_2
#define PWM_TIMER_1_GPIO_PA9_ALTFN GPIO_ALTFN_2
#define PWM_TIMER_1_GPIO_PA10_ALTFN GPIO_ALTFN_2
#define PWM_TIMER_1_GPIO_PA11_ALTFN GPIO_ALTFN_2
#define PWM_TIMER_1_GPIO_PE9_ALTFN GPIO_ALTFN_0
#define PWM_TIMER_1_GPIO_PE11_ALTFN GPIO_ALTFN_0
#define PWM_TIMER_1_GPIO_PE13_ALTFN GPIO_ALTFN_0
#define PWM_TIMER_1_GPIO_PE14_ALTFN GPIO_ALTFN_0

#define PWM_TIMER_3_GPIO_PA6_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PA7_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PB0_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PB1_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PB4_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PB5_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PC6_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PC7_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PC8_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PC9_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PE3_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PE4_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PE5_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_3_GPIO_PE6_ALTFN GPIO_ALTFN_1

#define PWM_TIMER_14_GPIO_PA4_ALTFN GPIO_ALTFN_4
#define PWM_TIMER_14_GPIO_PA7_ALTFN GPIO_ALTFN_4

#define PWM_TIMER_15_GPIO_PA2_ALTFN GPIO_ALTFN_0
#define PWM_TIMER_15_GPIO_PA3_ALTFN GPIO_ALTFN_0
#define PWM_TIMER_15_GPIO_PB14_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_15_GPIO_PB15_ALTFN GPIO_ALTFN_1
#define PWM_TIMER_15_GPIO_PF9_ALTFN GPIO_ALTFN_0
#define PWM_TIMER_15_GPIO_PF10_ALTFN GPIO_ALTFN_0

#define PWM_TIMER_16_GPIO_PA6_ALTFN GPIO_ALTFN_5
#define PWM_TIMER_16_GPIO_PB8_ALTFN GPIO_ALTFN_2
#define PWM_TIMER_16_GPIO_PE0_ALTFN GPIO_ALTFN_0

#define PWM_TIMER_17_GPIO_PA7_ALTFN GPIO_ALTFN_5
#define PWM_TIMER_17_GPIO_PB9_ALTFN GPIO_ALTFN_2
#define PWM_TIMER_17_GPIO_PE1_ALTFN GPIO_ALTFN_0
