#pragma once

// CAN related messages in the event queue
typedef enum {
  MOTOR_CONTROLLER_INTERFACE_EVENT_CAN_FAULT = 0,
  MOTOR_CONTROLLER_INTERFACE_EVENT_CAN_RX,
  MOTOR_CONTROLLER_INTERFACE_EVENT_CAN_TX,
  MOTOR_CONTROLLER_INTERFACE_EVENT_FIFO,
  NUM_MOTOR_CONTROLLER_INTERFACE_EVENTS_CAN,
} MotorControllerInterfaceEventsCAN;
