#!/usr/bin/env bash

# Check for any changes
if [[ -n $(git status --porcelain) ]]; then
  echo "Uncommitted changes detected! Cannot test for formatting."
  echo "Please commit all local changes before pushing."
  exit 1
fi

if [[ $(whoami) == 'vagrant' ]]; then
  make test_format
else
  vagrant ssh -c 'cd shared/firmware; make test_format'
fi

if [[ $? -ne 0 ]]; then
  echo "Formatting applied - adding new commit"
  git add .
  git commit -m "Formatting (Automated commit)"
  git push --no-verify
fi
