#!/usr/bin/env bash

# Check for any changes
if [[ -n $(git status --porcelain) ]]; then
  echo "Uncommitted changes detected! Cannot test for formatting."
  echo "Please commit all local changes before pushing."
  exit 1
fi

if [[ $(whoami) == 'vagrant' ]]; then
  make test_format || exit 1
else
  vagrant ssh -c 'cd shared/firmware; make test_format' || (echo "??" && exit 1)
fi

echo "Always blocking push for development"
exit 1
