#pragma once

#define MC_CFG_CAN_BITRATE CAN_HW_BITRATE_500KBPS

#define MC_CFG_RELAY_LEFT \
  { .port = GPIO_PORT_B, .pin = 3 }
#define MC_CFG_RELAY_RIGHT \
  { .port = GPIO_PORT_B, .pin = 9 }
#define MC_CFG_RELAY_DELAY_MS 1000

#define MC_CFG_MOTOR_CAN_ID_DC_LEFT 0x01
#define MC_CFG_MOTOR_CAN_ID_DC_RIGHT 0x02
#define MC_CFG_MOTOR_CAN_ID_MC_LEFT 0x03
#define MC_CFG_MOTOR_CAN_ID_MC_RIGHT 0x04
#define MC_CFG_MOTOR_MAX_BUS_CURRENT 65.0f

#define MC_CFG_CAN_SPI_PORT SPI_PORT_2
#define MC_CFG_CAN_SPI_BAUDRATE 6000000
#define MC_CFG_CAN_SPI_MOSI \
  { .port = GPIO_PORT_B, 15 }
#define MC_CFG_CAN_SPI_MISO \
  { .port = GPIO_PORT_B, 14 }
#define MC_CFG_CAN_SPI_SCLK \
  { .port = GPIO_PORT_B, 14 }
#define MC_CFG_CAN_SPI_CS \
  { .port = GPIO_PORT_B, 12 }
#define MC_CFG_CAN_SPI_INIT_PIN \
  { .port = GPIO_PORT_A, 8 }

#define MC_CFG_CAN_HEARTBEAT_PERIOD_S 1
