#pragma once

typedef enum {
  MOTOR_EVENT_CAN_TX,
  MOTOR_EVENT_CAN_RX,
  MOTOR_EVENT_CAN_FAULT,

  MOTOR_EVENT_DRIVE_MESSAGE,

  MOTOR_EVENT_MECH_BRAKE_ENGAGED,
  MOTOR_EVENT_MECH_BRAKE_DISENGAGED,

  MOTOR_EVENT_CRUISE_ENGAGED,
  MOTOR_EVENT_CRUISE_DISENGAGED,
} MotorEvent;
