#pragma once

// Digital input pin definitions

#define DRIVER_IO_POWER_SWITCH_PORT 2
#define DRIVER_IO_POWER_SWITCH_PIN  0

#define DRIVER_IO_DIRECTION_SELECTOR_PORT         1
#define DRIVER_IO_DIRECTION_SELECTOR_PIN_FORWARD  2
#define DRIVER_IO_DIRECTION_SELECTOR_PIN_REVERSE  3

#define DRIVER_IO_CRUISE_CONTROL_PORT 2
#define DRIVER_IO_CRUISE_CONTROL_PIN  4

#define DRIVER_IO_CRUISE_CONTROL_INC_PORT 2
#define DRIVER_IO_CRUISE_CONTROL_INC_PIN  5

#define DRIVER_IO_CRUISE_CONTROL_DEC_PORT 2
#define DRIVER_IO_CRUISE_CONTROL_DEC_PIN  6

#define DRIVER_IO_TURN_SIGNAL_PORT        2
#define DRIVER_IO_TURN_SIGNAL_PIN_RIGHT   7
#define DRIVER_IO_TURN_SIGNAL_PIN_LEFT    8

#define DRIVER_IO_HAZARD_LIGHT_PORT 2
#define DRIVER_IO_HAZARD_LIGHT_PIN  9

// Analog input pin definitions

#define DRIVER_IO_GAS_PEDAL_PORT  0
#define DRIVER_IO_GAS_PEDAL_PIN   1

#define DRIVER_IO_MECHANICAL_BRAKE_PORT 0
#define DRIVER_IO_MECHANICAL_BRAKE_PIN  0
