#pragma once

#define DRIVER_IO_GET_PIN(address) ((GPIOAddress)address.pin)
#define DRIVER_IO_NUM_ADDRESSES 12

// Digital address definitions

// Centre Console Addresses
#define DRIVER_IO_POWER_SWITCH              { GPIO_PORT_A, 10 }
#define DRIVER_IO_DIR_SELECT_FORWARD        { GPIO_PORT_A, 9 }
#define DRIVER_IO_DIR_SELECT_REVERSE        { GPIO_PORT_A, 8 }
#define DRIVER_IO_HEADLIGHT                 { GPIO_PORT_B, 15 }
#define DRIVER_IO_HAZARD_LIGHT              { GPIO_PORT_B, 14 }
#define DRIVER_IO_BRAKING_REGEN_INC         { GPIO_PORT_B, 13 }
#define DRIVER_IO_BRAKING_REGEN_DEC         { GPIO_PORT_B, 12 }

// Pedal Sensor Addresses
#define DRIVER_IO_ADC_INTERRUPT             { GPIO_PORT_B, 2 }
#define DRIVER_IO_PEDAL_SENSOR_SCL          { GPIO_PORT_B, 10 }
#define DRIVER_IO_PEDAL_SENSOR_SDA          { GPIO_PORT_B, 11 }

// Steering Wheel GPIO Expander
#define DRIVER_IO_GPIO_EXPANDER_INTERRUPT   { GPIO_PORT_A, 0 }
#define DRIVER_IO_GPIO_SCL                  { GPIO_PORT_B, 8 }
#define DRIVER_IO_GPIO_SDA                  { GPIO_PORT_B, 9 }

// Analog address definitions
#define DRIVER_IO_GAS_PEDAL                 { GPIO_PORT_A, 0 }
#define DRIVER_IO_MECHANICAL_BRAKE          { GPIO_PORT_A, 1 }

// Driver IO pin definitions
#define DRIVER_IO_POWER_SWITCH_PIN          DRIVER_IO_GET_PIN(DRIVER_IO_POWER_SWITCH)
#define DRIVER_IO_DIR_SELECT_PIN_FORWARD    DRIVER_IO_GET_PIN(DRIVER_IO_DIR_SELECT_FORWARD)
#define DRIVER_IO_DIR_SELECT_PIN_REVERSE    DRIVER_IO_GET_PIN(DRIVER_IO_DIR_SELECT_REVERSE)
#define DRIVER_IO_HEADLIGHT_PIN             DRIVER_IO_GET_PIN(DRIVER_IO_HEADLIGHT)
#define DRIVER_IO_HAZARD_LIGHT_PIN          DRIVER_IO_GET_PIN(DRIVER_IO_HAZARD_LIGHT)
#define DRIVER_IO_BRAKING_REGEN_INC_PIN     DRIVER_IO_GET_PIN(DRIVER_IO_BRAKING_REGEN_INC)
#define DRIVER_IO_BRAKING_REGEN_DEC_PIN     DRIVER_IO_GET_PIN(DRIVER_IO_BRAKING_REGEN_DEC)

#define DRIVER_IO_RIGHT_TURN_SIGNAL_PIN     GPIO_EXPANDER_PIN_0
#define DRIVER_IO_LEFT_TURN_SIGNAL_PIN      GPIO_EXPANDER_PIN_1
#define DRIVER_IO_CRUISE_CONTROL_PIN        GPIO_EXPANDER_PIN_2
#define DRIVER_IO_CRUISE_CONTROL_INC_PIN    GPIO_EXPANDER_PIN_3
#define DRIVER_IO_CRUISE_CONTROL_DEC_PIN    GPIO_EXPANDER_PIN_4
#define DRIVER_IO_PUSH_TO_TALK_PIN          GPIO_EXPANDER_PIN_5
#define DRIVER_IO_BMS_FAULT_PIN             GPIO_EXPANDER_PIN_6
#define DRIVER_IO_HORN_PIN                  GPIO_EXPANDER_PIN_7

#define DRIVER_IO_GAS_PEDAL_PIN             DRIVER_IO_GET_PIN(DRIVER_IO_GAS_PEDAL)
#define DRIVER_IO_MECHANICAL_BRAKE_PIN      DRIVER_IO_GET_PIN(DRIVER_IO_MECHANICAL_BRAKE)
