#pragma once

// Driver IO pin definitions

#define DRIVER_IO_POWER_SWITCH_PIN          0
#define DRIVER_IO_DIR_SELECT_PIN_FORWARD    2
#define DRIVER_IO_DIR_SELECT_PIN_REVERSE    3
#define DRIVER_IO_CRUISE_CONTROL_PIN        4
#define DRIVER_IO_CRUISE_CONTROL_INC_PIN    5
#define DRIVER_IO_CRUISE_CONTROL_DEC_PIN    6
#define DRIVER_IO_TURN_SIGNAL_PIN_RIGHT     7
#define DRIVER_IO_TURN_SIGNAL_PIN_LEFT      8
#define DRIVER_IO_HAZARD_LIGHT_PIN          9

#define DRIVER_IO_GAS_PEDAL_PIN             0
#define DRIVER_IO_MECHANICAL_BRAKE_PIN      1

// Digital address definitions

#define DRIVER_IO_POWER_SWITCH              { GPIO_PORT_C, DRIVER_IO_POWER_SWITCH_PIN }
#define DRIVER_IO_DIR_SELECT_FORWARD        { GPIO_PORT_B, DRIVER_IO_DIR_SELECT_PIN_FORWARD }
#define DRIVER_IO_DIR_SELECT_REVERSE        { GPIO_PORT_B, DRIVER_IO_DIR_SELECT_PIN_REVERSE }
#define DRIVER_IO_CRUISE_CONTROL_PORT       { GPIO_PORT_C, DRIVER_IO_CRUISE_CONTROL_PIN }
#define DRIVER_IO_CRUISE_CONTROL_INC        { GPIO_PORT_C, DRIVER_IO_CRUISE_CONTROL_INC_PIN }
#define DRIVER_IO_CRUISE_CONTROL_DEC        { GPIO_PORT_C, DRIVER_IO_CRUISE_CONTROL_DEC_PIN }
#define DRIVER_IO_TURN_SIGNAL_RIGHT         { GPIO_PORT_C, DRIVER_IO_TURN_SIGNAL_PIN_RIGHT }
#define DRIVER_IO_TURN_SIGNAL_LEFT          { GPIO_PORT_C, DRIVER_IO_TURN_SIGNAL_PIN_LEFT }
#define DRIVER_IO_HAZARD_LIGHT              { GPIO_PORT_C, DRIVER_IO_HAZARD_LIGHT_PIN }

// Analog address definitions

#define DRIVER_IO_GAS_PEDAL                 { GPIO_PORT_A, DRIVER_IO_GAS_PEDAL_PIN }
#define DRIVER_IO_MECHANICAL_BRAKE          { GPIO_PORT_A, DRIVER_IO_MECHANICAL_BRAKE_PIN }
