#pragma once

// Digital Inputs
#define STEERING_CONFIG_PIN_HORN \
  { GPIO_PORT_B, 1 }
#define STEERING_CONFIG_PIN_HIGH_BEAM_BACK \
  { GPIO_PORT_B, 0 }
#define STEERING_CONFIG_PIN_HIGH_BEAM_FWD \
  { GPIO_PORT_A, 7 }
#define STEERING_CONFIG_PIN_LANE_ASSIST \
  { GPIO_PORT_A, 6 }
#define STEERING_CONFIG_PIN_CC_ON_OFF \
  { GPIO_PORT_A, 5 }
#define STEERING_CONFIG_PIN_CC_SET \
  { GPIO_PORT_A, 4 }

// Analog Inputs
#define STEERING_CONFIG_PIN_TURN_SIGNAL_STALK \
  { GPIO_PORT_A, 0 }
#define STEERING_CONFIG_PIN_CC_CANCEL_RESUME \
  { GPIO_PORT_A, 1 }
#define STEERING_CONFIG_PIN_CC_SPEED \
  { GPIO_PORT_A, 2 }
#define STEERING_CONFIG_PIN_CC_DISTANCE \
  { GPIO_PORT_A, 3 }

// CAN
#define STEERING_CONFIG_PIN_CAN_TX \
  { GPIO_PORT_A, 12 }
#define STEERING_CONFIG_PIN_CAN_RX \
  { GPIO_PORT_A, 11 }
