#pragma once

#include "event_queue.h"

typedef enum {
  // CAN events
  INPUT_EVENT_STEERING_WATCHDOG_FAULT = 0,
  INPUT_EVENT_STEERING_CAN_RX,
  INPUT_EVENT_STEERING_CAN_TX,
  INPUT_EVENT_STEERING_CAN_FAULT,
  INPUT_EVENT_STEERING_UPDATE_REQUESTED,

  NUM_STEERING_INPUT_EVENTS,
} InputEvent;