#pragma once

// This module holds the storage for lights_gpio when operating on the rear board.

// All the rear board peripherals.
typedef enum {
  LIGHTS_GPIO_CONFIG_REAR_PERIPHERAL_STROBE = 0,         //
  LIGHTS_GPIO_CONFIG_REAR_PERIPHERAL_RIGHT_BRAKE,        //
  LIGHTS_GPIO_CONFIG_REAR_PERIPHERAL_RIGHT_OUTER_BRAKE,  //
  LIGHTS_GPIO_CONFIG_REAR_PERIPHERAL_LEFT_BRAKE,         //
  LIGHTS_GPIO_CONFIG_REAR_PERIPHERAL_LEFT_OUTER_BRAKE,   //
  LIGHTS_GPIO_CONFIG_REAR_PERIPHERAL_CENTRE_BRAKE,       //
  LIGHTS_GPIO_CONFIG_REAR_PERIPHERAL_LEFT_OUTER_TURN,    //
  LIGHTS_GPIO_CONFIG_REAR_PERIPHERAL_LEFT_TURN,          //
  LIGHTS_GPIO_CONFIG_REAR_PERIPHERAL_RIGHT_OUTER_TURN,   //
  LIGHTS_GPIO_CONFIG_REAR_PERIPHERAL_RIGHT_TURN,         //
  NUM_LIGHTS_GPIO_CONFIG_REAR_PERIPHERALS,               //
} LightsGPIOConfigRearPeripherals;

// Config for rear board.
LightsGPIO *lights_config_rear_load(void);
