#pragma once

typedef enum {
  SOLAR_MASTER_EVENT_CAN_RX = 0,
  SOLAR_MASTER_EVENT_CAN_TX,
  SOLAR_MASTER_EVENT_CAN_FAULT,
  SOLAR_MASTER_EVENT_RELAY_STATE,
  NUM_SOLAR_MASTER_EVENTS
} SolarMasterEvent;
